In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Dataset_Praktikum_BI_300Rows_Dirty.csv to Dataset_Praktikum_BI_300Rows_Dirty.csv

In [ ]:
df=pd.read_csv("Dataset_Praktikum_BI_300Rows_Dirty.csv")
df.shape

(300, 9)

In [ ]:
df.head()

,Order_ID,Order_Date,Customer_ID,Region,Product_Category,Product_Name,Quantity,Unit_Price,Total_Sales
0,ORD001,10/01/2025,C090,Timur,Elektronik,Headphone,1.0,3466191.0,3466191.0
1,ORD002,07/04/2025,C102,Barat,Fashion,Sepatu,4.0,784955.0,3139820.0
2,ORD003,10/01/2025,C104,Tengah,Home & Living,Karpet,5.0,4050723.0,20253615.0
3,ORD004,13/06/2025,C109,TIMUR,Elektronik,Tablet,5.0,3693899.0,18469495.0
4,ORD005,2025-03-28,C076,Barat,Fashion,Sepatu,4.0,2246869.0,8987476.0

In [ ]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Region,Product_Category,Product_Name,Quantity,Unit_Price,Total_Sales
295,ORD296,12/06/2025,C067,Utara,Fashion,Kaos,4.0,2155190.0,8620760.0
296,ORD297,27/04/2025,C066,Selatan,Fashion,Sepatu,2.0,1759208.0,3518416.0
297,ORD298,31/05/2025,C089,TIMUR,Fashion,Tas,2.0,4599455.0,9198910.0
298,ORD299,11/03/2025,C072,Barat,Home & Living,Lampu,5.0,58778.0,293890.0
299,ORD300,30/05/2025,C025,barat,Olahraga,NaN,4.0,2813686.0,11254744.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          300 non-null    object
 1   Order_Date        300 non-null    object
 2   Customer_ID       300 non-null    object
 3   Region            300 non-null    object
 4   Product_Category  300 non-null    object
 5   Product_Name      279 non-null    object
 6   Quantity          288 non-null    float64
 7   Unit_Price        288 non-null    float64
 8   Total_Sales       285 non-null    float64
dtypes: float64(3), object(6)
memory usage: 21.2+ KB

In [ ]:
print(df.isnull().sum())

Order_ID             0
Order_Date           0
Customer_ID          0
Region               0
Product_Category     0
Product_Name        21
Quantity            12
Unit_Price          12
Total_Sales         15
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# Standarisasi teks
df['Region'] = df ['Region'].str.strip().str.title()
df['Product_Category'] = df['Product_Category'].str.strip().str.title()
df['Product_Name'] = df['Product_Name'].str.strip().str.title()

In [ ]:
# Mengisi Nilai  Quantity jika memungkinkan (Total Sales dan Unit Price Ada)
df.loc[
    (df['Quantity'].isnull()) &
    (df['Unit_Price'].notnull()) &
    (df['Total_Sales'].notnull()),
    'Quantity'
] = df['Total_Sales'] / df['Unit_Price']


# Mengisi Nilai  Unit_Price jika memungkinkan (Total Sales dan Quantity ada)
df.loc[
    (df['Unit_Price'].isnull()) &
    (df['Quantity'].notnull()) &
    (df['Total_Sales'].notnull()),
    'Unit_Price'
] = df['Total_Sales'] / df['Quantity']


# Jika masih kosong → isi median
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].median())



# Numerik diisi median (nilai tengah)
#df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
#df['Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].median())


# Kategori diisi modus (nilai sering muncul)
df['Product_Name'] = df.groupby('Product_Category')['Product_Name']\
  .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else x))

In [ ]:
# Untuk menghitung total sales
df['Total_Sales'] = df['Quantity'] * df['Unit_Price']

In [ ]:
# Mengubah tipe data
df['Quantity'] = df['Quantity'].astype(int)
df['Unit_Price'] = df['Unit_Price'].astype(float)
df['Total_Sales'] = df['Total_Sales'].astype(float)

In [ ]:
# KONVERSI ORDER DATE
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='coerce')

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          300 non-null    object
 1   Order_Date        300 non-null    datetime64[ns]
 2   Customer_ID       300 non-null    object
 3   Region            300 non-null    object
 4   Product_Category  300 non-null    object
 5   Product_Name      300 non-null    object
 6   Quantity          300 non-null    int64
 7   Unit_Price        300 non-null    float64
 8   Total_Sales       300 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 21.2+ KB
None

In [ ]:
print(df.isnull().sum())

Order_ID            0
Order_Date          0
Customer_ID         0
Region              0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Total_Sales         0
dtype: int64

In [ ]:
print(df.head())
print(df.tail())

  Order_ID Order_Date Customer_ID  Region Product_Category Product_Name  \
0   ORD001 2025-10-01        C090   Timur       Elektronik    Headphone
1   ORD002 2025-07-04        C102   Barat          Fashion       Sepatu
2   ORD003 2025-10-01        C104  Tengah    Home & Living       Karpet
3   ORD004 2025-06-13        C109   Timur       Elektronik       Tablet
4   ORD005 2025-03-28        C076   Barat          Fashion       Sepatu

   Quantity  Unit_Price  Total_Sales
0         1   3466191.0    3466191.0
1         4    784955.0    3139820.0
2         5   4050723.0   20253615.0
3         5   3693899.0   18469495.0
4         4   2246869.0    8987476.0
    Order_ID Order_Date Customer_ID   Region Product_Category Product_Name  \
295   ORD296 2025-12-06        C067    Utara          Fashion         Kaos
296   ORD297 2025-04-27        C066  Selatan          Fashion       Sepatu
297   ORD298 2025-05-31        C089    Timur          Fashion          Tas
298   ORD299 2025-11-03        C072    Barat    Home & Living        Lampu
299   ORD300 2025-05-30        C025    Barat         Olahraga         Bola

     Quantity  Unit_Price  Total_Sales
295         4   2155190.0    8620760.0
296         2   1759208.0    3518416.0
297         2   4599455.0    9198910.0
298         5     58778.0     293890.0
299         4   2813686.0   11254744.0

In [ ]:
df.to_csv("Dataset_Praktikum_Clean.csv", index=False)

In [ ]:
from google.colab import files
files.download("Dataset_Praktikum_Clean.csv")